[package]
name = "multi-party-schnorr"
version = "0.1.0"
authors = [
    "Omer <omer@kzencorp.com>",
    "Gary <gary@kzencorp.com>"
]

[lib]
crate-type = ["lib"]

[dependencies]
curv = { git = "https://github.com/KZen-networks/curv" , branch = "des", features =  ["curvesecp256k1"]}

[dependencies.centipede]
git = "https://github.com/KZen-networks/centipede"
branch = "des"



[dev-dependencies]
hex = "0.3.2"

